export const CHANGE_LOADINGBAR = "CHANGE_LOADINGBAR";
export const ADD_FILTER = "ADD_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";
export const UPDATE_FILTER_COUNT = "UPDATE_FILTER_COUNT";
export const REMOVE_SINGLE_FILTER = "REMOVE_SINGLE_FILTER";
